export default {
  LOAD_PRODUCT_REQUEST : 'LOAD_PRODUCT_REQUEST',
  LOAD_PRODUCT_SUCCESS : 'LOAD_PRODUCT_SUCCESS',
  LOAD_PRODUCT_FAILED : 'LOAD_PRODUCT_FAILED',
  ADD_PRODUCT_SUCCESS : 'ADD_PRODUCT_SUCCESS',
  ADD_PRODUCT_REQUEST : 'ADD_PRODUCT_REQUEST',
  ADD_PRODUCT_FAILED : 'ADD_PRODUCT_FAILED',
  ADD_PRODUCT_STATE:'ADD_PRODUCT_STATE',
  DETETE_PRODUCT : 'DETETE_PRODUCT',
  LOAD_NEW_ENTRY:'LOAD_NEW_ENTRY',
  LOAD_PRODUCT_PROMOTE:'LOAD_PRODUCT_PROMOTE'
  
}