export default {
  LOAD_PRODUCT_REQUEST : 'LOAD_PRODUCT_REQUEST',
  LOAD_PRODUCT_SUCCESS : 'LOAD_PRODUCT_SUCCESS',
  LOAD_PRODUCT_FAILED : 'LOAD_PRODUCT_FAILED',
  LOAD_PRODUCT_BY_NAME : 'LOAD_PRODUCT_BY_NAME',
  ADD_PRODUCT_SUCCESS : 'ADD_PRODUCT_SUCCESS',
  ADD_PRODUCT_REQUEST : 'ADD_PRODUCT_REQUEST',
  ADD_PRODUCT_FAILED : 'ADD_PRODUCT_FAILED',
  ADD_PRODUCT_STATE:'ADD_PRODUCT_STATE',
  DETETE_PRODUCT : 'DETETE_PRODUCT',
  LOAD_NEW_ENTRY:'LOAD_NEW_ENTRY',
  LOAD_PRODUCT_PROMOTE:'LOAD_PRODUCT_PROMOTE',
  LOAD_USER_INFO:'LOAD_USER_INFO',
  ADD_ROUTE_INFO:'ADD_ROUTE_INFO',
  SIGNIN_DIALOG_SET_TOGGLE:'SIGNIN_DIALOG_SET_TOGGLE',
  SIGNUP_DIALOG_SET_TOGGLE:'SIGNUP_DIALOG_SET_TOGGLE',
  SIGNUP_DIALOG_SHOW_ADDR:'SIGNUP_DIALOG_SHOW_ADDR',
  CHANGEEMAIL_DIALOG_SET_TOGGLE:'CHANGEEMAIL_DIALOG_SET_TOGGLE'
  
}